# object pose estimation service 

sensor_msgs/Image color_image   # color image of scene
sensor_msgs/Image depth_image   # depth image of scene
naviai_manip_msgs/DetItem[] items    # message from segmentation, each item including label, confidence, bbox and mask
---
naviai_manip_msgs/ObjPose[] obj_poses   # the list of estimated poses, including object labels and estimated poses 
